name: Go CI

on:
  push:
    branches:
      - svil

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Run tidy
      run: go mod tidy -e 

    - name: Run unit tests
      run: go test -v ./...
