name: CI/CD pipeline

on:
  push:
    branches:
      - main

env:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: |
        go get -v -t -d ./...

    - name: Build and test
      run: |
        go test -v ./...

    - name: Build binary
      run: |
        go build -o main

  integration-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PostgreSQL
      uses: bitnami/bitnami-action-postgresql@v1
      with:
        POSTGRESQL_ROOT_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        POSTGRESQL_DATABASE: testdb
        POSTGRESQL_USERNAME: ${{ env.POSTGRES_USERNAME }}
        POSTGRESQL_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

    - name: Run integration tests
      run: |
        go test -v ./... -run TestIntegration
