name: CI/CD pipeline

on:
  push:
    branches:
      - main

env:
  env:
  POSTGRES_HOST: 192.168.1.16
  POSTGRES_PORT: 5660
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: |
        go get -v -t -d ./...

    - name: Build and test
      run: |
        go test -v ./...

    - name: Build binary
      run: |
        go build -o main

  integration-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Go REST API Tests
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      env:
        POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
        POSTGRES_DB: ${{ env.POSTGRES_DB }}
        POSTGRES_USER: ${{ env.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      run: |
        go test ./...
