name: Go REST API Workflow

on:
  push:
    branches:
      - svil

env:
  POSTGRES_HOST: 192.168.1.16
  POSTGRES_PORT: 5660
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PostgreSQL
      uses: postgresql/setup-postgresql@v1
      with:
        version: 11
        postgresql-port: ${{ env.POSTGRES_PORT }}

    - name: Run Go REST API Tests
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      env:
        POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
        POSTGRES_DB: ${{ env.POSTGRES_DB }}
        POSTGRES_USER: ${{ env.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      run: |
        go test ./...
