name: Go REST API and PostgreSQL Workflow

on:
  push:
    branches:
      - svil

env:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Install dependencies
      run: |
        go get -v ./...

    - name: Test API
      run: |
        go test ./...

    - name: Start PostgreSQL
      uses: sameersbn/action-postgresql@v0.6.0
      with:
        POSTGRES_DB: ${{ env.POSTGRES_DB }}
        POSTGRES_USER: ${{ env.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

    - name: Test API with PostgreSQL
      run: |
        go test -v -tags=integration ./...
